# Generated by Django 3.0.2 on 2020-04-18 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aucPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aucBidder', models.CharField(max_length=60)),
                ('aucStatus', models.BooleanField()),
                ('aucDateTimeCountdown', models.DateTimeField()),
                ('aucWinner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmTitle', models.CharField(max_length=60)),
                ('itmTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('itmCondition', models.BooleanField()),
                ('itmDescription', models.CharField(max_length=100)),
                ('itmExpireDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('itmOwner', models.CharField(max_length=60)),
            ],
        ),
    ]
