# Generated by Django 3.0.2 on 2020-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200418_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='aucStatus',
            new_name='aucOpen',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itmCondition',
            new_name='itmIsNew',
        ),
    ]
