# Generated by Django 3.0.2 on 2020-04-18 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200418_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='aucOpen',
        ),
        migrations.AddField(
            model_name='auction',
            name='aucIsOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itmExpireDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 19, 8, 35, 664814, tzinfo=utc)),
        ),
    ]
