# Generated by Django 3.0.2 on 2020-04-28 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200418_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='itemID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='itmExpireDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
