# Generated by Django 3.0.2 on 2020-04-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200428_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='itemID',
        ),
    ]
