# Generated by Django 3.0.2 on 2020-04-28 15:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200428_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='aucPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
