# Generated by Django 3.0.2 on 2020-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200428_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='aucPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
